name: MultiWorld
author: CzechPMDevs
authors: [GamakCZ]
api: [3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALHPA6]
version: 1.3.0 [BETA 3] [Genisys]
main: MultiWorld\MultiWorld
description: Ported MultiWorld to pocketmine.
website: https://github.com/CzechPMDevs/MultiWorld

commands:
  multiworld:
    aliases: [mw, wm]
    description: MultiWorld commands

permissions:
  mw.cmd:
    default: op
    description: Permission for all MultiWorld commands
    childern:
      mw.cmd.create:
        description: Permission for /mw create
        default: op
      mw.cmd.delete:
        description: Permission for /mw delete
        default: op
      mw.cmd.help:
        description: Permission for /mw help
        default: op
      mw.cmd.import:
        description: Permission for /mw import
        default: op
      mw.cmd.list:
        description: Permission for /mw list
        default: op
      mw.cmd.load:
        description: Permission for /mw load
        default: op
      mw.cmd.setlobby:
        description: Prmission for /mw setlobby
        default: op
      mw.cmd.setdefault:
        description: Permission for /mw setdefault
        default: op
      mw.cmd.sethub:
        description: Permission for /mw sethub
        default: op
      mw.cmd.teleport:
        description: Permission for /mw teleport
        default: op
      mw.cmd.unload:
        description: Permission for /mw unload
        default: op
